# -*- coding: utf-8 -*-
"""teste_notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rjtxoDSN9KKSU7mWuBcGz-7EsEimyD8F
"""

teste=('Hello World')
print(teste)